# -*- coding: utf-8 -*-
"""
全球智库 · 智库源配置
S/A/B三级智库注册表
"""

# ── 端口 ──
PORT = 4002

# ── S级：全球顶级核心智库（战略级情报来源）──
TIER_S_SOURCES = [
    {
        "id": "csis",
        "name": "CSIS",
        "full_name": "Center for Strategic and International Studies",
        "country": "US",
        "region": "北美",
        "tier": "S",
        "feed_url": "https://www.csis.org/rss.xml",
        "feed_type": "rss",
        "homepage": "https://www.csis.org",
        "lang": "en",
        "domains": ["战略安全", "地缘政治", "科技政策", "能源安全"],
        "polling_minutes": 240,
    },
    {
        "id": "brookings",
        "name": "Brookings",
        "full_name": "Brookings Institution",
        "country": "US",
        "region": "北美",
        "tier": "S",
        "feed_url": "https://www.brookings.edu/feed/",
        "feed_type": "rss",
        "homepage": "https://www.brookings.edu",
        "lang": "en",
        "domains": ["宏观经济", "全球治理", "社会发展"],
        "polling_minutes": 240,
    },
    {
        "id": "cfr",
        "name": "CFR",
        "full_name": "Council on Foreign Relations",
        "country": "US",
        "region": "北美",
        "tier": "S",
        "feed_url": "https://www.cfr.org/api/headline.json",
        "feed_type": "api",
        "homepage": "https://www.cfr.org",
        "lang": "en",
        "domains": ["外交政策", "国家安全", "国际经济"],
        "polling_minutes": 240,
    }, 
    {
        "id": "rand",
        "name": "RAND",
        "full_name": "RAND Corporation",
        "country": "US",
        "region": "北美",
        "tier": "S",
        "feed_url": "https://www.rand.org/topics.xml",
        "feed_type": "rss",
        "homepage": "https://www.rand.org",
        "lang": "en",
        "domains": ["国防安全", "科技政策", "公共政策"],
        "polling_minutes": 240,
    }, 
    {
        "id": "chatham",
        "name": "Chatham House",
        "full_name": "Chatham House / Royal Institute of International Affairs",
        "country": "UK",
        "region": "欧洲",
        "tier": "S",
        "feed_url": "https://www.chathamhouse.org/whatsnew.xml",
        "feed_type": "rss",
        "homepage": "https://www.chathamhouse.org",
        "lang": "en",
        "domains": ["国际事务", "能源环境", "全球经济"],
        "polling_minutes": 240,
    }, 
    {
        "id": "sipri",
        "name": "SIPRI",
        "full_name": "Stockholm International Peace Research Institute",
        "country": "SE",
        "region": "欧洲",
        "tier": "S",
        "feed_url": "https://www.sipri.org/publications/feed.xml",
        "feed_type": "rss",
        "homepage": "https://www.sipri.org",
        "lang": "en",
        "domains": ["军控", "国防开支", "安全研究"],
        "polling_minutes": 360,
    }, 
    {
        "id": "carnegie",
        "name": "Carnegie",
        "full_name": "Carnegie Endowment for International Peace",
        "country": "US",
        "region": "全球",
        "tier": "S",
        "feed_url": "https://carnegieendowment.org/feed/",
        "feed_type": "rss",
        "homepage": "https://carnegieendowment.org",
        "lang": "en",
        "domains": ["全球治理", "核不扩散", "中美关系"],
        "polling_minutes": 240,
    }, 
    {
        "id": "piie",
        "name": "Peterson IIE",
        "full_name": "Peterson Institute for International Economics",
        "country": "US",
        "region": "北美",
        "tier": "S",
        "feed_url": "https://www.piie.com/feed/",
        "feed_type": "rss",
        "homepage": "https://www.piie.com",
        "lang": "en",
        "domains": ["国际贸易", "汇率政策", "全球经济"],
        "polling_minutes": 240,
    }, 
    {
        "id": "cass",
        "name": "CASS",
        "full_name": "Chinese Academy of Social Sciences",
        "country": "CN",
        "region": "亚太",
        "tier": "S",
        "feed_url": "",
        "feed_type": "web",
        "homepage": "https://www.cass.cn",
        "lang": "zh",
        "domains": ["宏观经济", "国际关系", "产业政策"],
        "polling_minutes": 360,
    },
    {
        "id": "drc",
        "name": "DRC",
        "full_name": "Development Research Center of the State Council",
        "country": "CN",
        "region": "亚太",
        "tier": "S",
        "feed_url": "",
        "feed_type": "web",
        "homepage": "https://www.drc.gov.cn",
        "lang": "zh",
        "domains": ["产业政策", "经济改革", "发展研究"],
        "polling_minutes": 360,
    },
]

# ── A级：区域标杆智库 ──
TIER_A_SOURCES = [
    {
        "id": "ifri",
        "name": "IFRI",
        "full_name": "French Institute of International Relations",
        "country": "FR",
        "region": "欧洲",
        "tier": "A",
        "feed_url": "https://www.ifri.org/rss.xml",
        "feed_type": "rss",
        "lang": "fr",
        "domains": ["欧洲安全", "防务", "国际关系"],
        "polling_minutes": 1440,
    },
    {
        "id": "swp",
        "name": "SWP",
        "full_name": "Stiftung Wissenschaft und Politik",
        "country": "DE",
        "region": "欧洲",
        "tier": "A",
        "feed_url": "https://www.swp-berlin.org/rss.xml",
        "feed_type": "rss",
        "lang": "de",
        "domains": ["德国外交", "欧盟政策", "安全研究"],
        "polling_minutes": 1440,
    },
    {
        "id": "lowy",
        "name": "Lowy Institute",
        "full_name": "Lowy Institute for International Policy",
        "country": "AU",
        "region": "亚太",
        "tier": "A",
        "feed_url": "https://www.lowyinstitute.org/feed/",
        "feed_type": "rss",
        "lang": "en",
        "domains": ["印太战略", "澳大利亚外交", "区域安全"],
        "polling_minutes": 1440,
    }, 
    {
        "id": "iseas",
        "name": "ISEAS",
        "full_name": "ISEAS–Yusof Ishak Institute",
        "country": "SG",
        "region": "亚太",
        "tier": "A",
        "feed_url": "https://www.iseas.edu.sg/rss.xml",
        "feed_type": "rss",
        "lang": "en",
        "domains": ["东南亚政治", "东盟经济", "区域合作"],
        "polling_minutes": 1440,
    },
    {
        "id": "cf40",
        "name": "CF40",
        "full_name": "China Finance 40 Forum",
        "country": "CN",
        "region": "亚太",
        "tier": "A",
        "feed_url": "",
        "feed_type": "web",
        "homepage": "https://www.cf40.com",
        "lang": "zh",
        "domains": ["金融政策", "人民币国际化", "金融监管"],
        "polling_minutes": 1440,
    },
    {
        "id": "siis",
        "name": "SIIS",
        "full_name": "Shanghai Institutes for International Studies",
        "country": "CN",
        "region": "亚太",
        "tier": "A",
        "feed_url": "",
        "feed_type": "web",
        "homepage": "https://www.siis.org.cn",
        "lang": "zh",
        "domains": ["亚太安全", "上海合作", "大国关系"],
        "polling_minutes": 1440,
    },
]

# ── 全部智库列表 ──
ALL_SOURCES = TIER_S_SOURCES + TIER_A_SOURCES

# ── 领域标签体系 ──
DOMAIN_TAGS = [
    "战略安全与地缘政治",
    "宏观经济与金融政策",
    "科技前沿与产业创新",
    "能源、气候与环境",
    "公共卫生与社会治理",
    "国际贸易与规则博弈",
    "军事与防务安全",
    "数字经济与人工智能",
]

# ── 地缘区域标签 ──
REGION_TAGS = [
    "北美", "欧洲", "亚太", "中东中亚", "拉美非洲", "全球",
]

# ── 地区 → 国家 → 领域 (三级标签映射) ──
DOMAIN_TO_KEYWORDS = {
    "战略安全与地缘政治": ["security", "geopolitical", "defense", "conflict", "nuclear",
                         "alliance", "geopolitics", "战略", "安全", "地缘", "冲突"],
    "宏观经济与金融政策": ["economy", "monetary", "fiscal", "inflation", "gdp",
                         "interest rate", "debt", "宏观经济", "金融", "通胀", "GDP"],
    "科技前沿与产业创新": ["technology", "innovation", "semiconductor", "AI", "quantum",
                         "tech", "科技", "半导体", "人工智能", "创新"],
    "能源、气候与环境": ["energy", "climate", "environment", "renewable", "oil",
                        "green", "能源", "气候", "环境", "碳中和"],
    "公共卫生与社会治理": ["health", "pandemic", "social", "governance", "demographic",
                         "public health", "公共卫生", "社会治理", "人口"],
    "国际贸易与规则博弈": ["trade", "tariff", "export control", "WTO", "supply chain",
                        "贸易", "关税", "出口管制", "供应链"],
    "军事与防务安全": ["military", "arms", "defense spending", "navy", "cyber warfare",
                     "军事", "军控", "国防", "网络战"],
    "数字经济与人工智能": ["digital", "AI", "data", "platform", "blockchain",
                         "web3", "数字经济", "AI", "数据", "区块链"],
}

# ── 情绪词典 ──
SENTIMENT_POSITIVE = ["breakthrough", "growth", "opportunity", "stable", "progress",
                      "突破", "增长", "机会", "稳定", "进步"]
SENTIMENT_NEGATIVE = ["risk", "threat", "decline", "crisis", "conflict", "sanction",
                      "风险", "威胁", "下降", "危机", "冲突", "制裁"]
