trustPolicyExclude:
  - 'detect-port@1.6.1'
  - 'chokidar@4.0.3'

packages:
  - 'apps/*'
  - 'libs/*'
  - 'tools/*'

onlyBuiltDependencies:
  - '@alicloud/openapi-core'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - esbuild
  - git-commit-msg-linter
  - msgpackr-extract
  - nx
  - protobufjs
  - sharp
  - simple-git-hooks
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - axios

allowBuilds:
  '@alicloud/openapi-core': false
  '@nestjs/core': false
  '@scarf/scarf': false
  esbuild: false
  git-commit-msg-linter: false
  msgpackr-extract: false
  nx: false
  protobufjs: false
  sharp: false
  simple-git-hooks: false
  unrs-resolver: false
